services:
  site1:
    build: .
    container_name: site1
    env_file:
      - .env
    environment:
      - NAME=site1
      - RANGE_START=None
      - RANGE_END=3300
      - PEER_LOWER=None
      - PEER_HIGHER=site2
    ports:
      - "8001:8000"

  site2:
    build: .
    container_name: site2
    env_file:
      - .env
    environment:
      - NAME=site2
      - RANGE_START=3301
      - RANGE_END=6600
      - PEER_LOWER=site1
      - PEER_HIGHER=site3
    ports:
      - "8002:8000"

  site3:
    build: .
    container_name: site3
    env_file:
      - .env
    environment:
      - NAME=site3
      - RANGE_START=6601
      - RANGE_END=None
      - PEER_LOWER=site2
      - PEER_HIGHER=None
    ports:
      - "8003:8000"

  simulation:
    build: .
    container_name: simulation
    env_file:
      - .env
    environment:
      - TARGET_HOST=site1:8000
      - STARTUP_DELAY=10
    volumes:
      - ./results:/app/results
    command: python user_simulation.py
    depends_on:
      - site1
      - site2
      - site3
