# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skiplist.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skiplist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eskiplist.proto\"j\n\x0fSkipListRequest\x12\x17\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x07.Action\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0c\n\x04hops\x18\x03 \x01(\r\x12\x15\n\x08isServer\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x0b\n\t_isServer\"o\n\x10SkipListResponse\x12\x13\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x05.Code\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x0c\n\x04hops\x18\x03 \x01(\r\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_dataB\x08\n\x06_error*A\n\x06\x41\x63tion\x12\x11\n\rACTION_INSERT\x10\x00\x12\x11\n\rACTION_DELETE\x10\x01\x12\x11\n\rACTION_SEARCH\x10\x02*<\n\x04\x43ode\x12\x10\n\x0c\x43ODE_SUCCESS\x10\x00\x12\x12\n\x0e\x43ODE_NOT_FOUND\x10\x01\x12\x0e\n\nCODE_ERROR\x10\x03\x32G\n\x0fSkipListService\x12\x34\n\x0bSendRequest\x12\x10.SkipListRequest\x1a\x11.SkipListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skiplist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=239
  _globals['_ACTION']._serialized_end=304
  _globals['_CODE']._serialized_start=306
  _globals['_CODE']._serialized_end=366
  _globals['_SKIPLISTREQUEST']._serialized_start=18
  _globals['_SKIPLISTREQUEST']._serialized_end=124
  _globals['_SKIPLISTRESPONSE']._serialized_start=126
  _globals['_SKIPLISTRESPONSE']._serialized_end=237
  _globals['_SKIPLISTSERVICE']._serialized_start=368
  _globals['_SKIPLISTSERVICE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
