syntax = "proto3";

enum Action {
    ACTION_INSERT = 0;
    ACTION_DELETE = 1;
    ACTION_SEARCH = 2;
}

enum Code{
    CODE_SUCCESS = 0;
    CODE_NOT_FOUND = 1;
    CODE_ERROR = 3;
}

message SkipListRequest{
    Action action = 1; // an enum containing the action (search, delete, insert)
    bytes data = 2; // the data sent coded as bytes
    uint32 hops = 3; // uint counter for the network hops
}

message SkipListResponse{
    Code code = 1; // an enum representing the result of the action (success, not found, error)
    optional bytes data = 2; // option data return as byts
    uint32 hops = 3; // uint counter for the network hops
    optional string error = 4; // optional string containing error message if code == error
}

service SkipListService{
    // api endpoint recieves SkipListRequest and returns SkipListResponse
    rpc SendRequest (SkipListRequest) returns (SkipListResponse){} 
}